name = "Create Mod Island With Blocky and Frogy"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c2cdafa99c9d119e4a709f07512f1d007a663dc2d237e4523c3b7f8775ddf0a"

[versions]
fabric = "0.17.0"
minecraft = "1.20.1"
